# -*- coding: utf-8 -*-
"""automate_Amar_Djidan_Hasibuan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xn-KUM3ggzBoIAaQnjv-mAGAjYCsatZd
"""

import pandas as pd


def preprocessing_data(input_file, output_file):

    # Load dataset
    df = pd.read_csv(input_file)

    # Hapus missing value
    df = df.dropna()

    # Hapus duplikat
    df = df.drop_duplicates()

    # Konversi tanggal
    df['date'] = pd.to_datetime(df['date'])

    # Feature engineering
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    df['day'] = df['date'].dt.day
    df['dayofweek'] = df['date'].dt.dayofweek

    # Outlier handling metode IQR
    Q1 = df['sales'].quantile(0.25)
    Q3 = df['sales'].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[
        (df['sales'] >= lower) &
        (df['sales'] <= upper)
    ]

    # Hapus kolom tanggal
    df = df.drop(columns=['date'])

    # Simpan hasil
    df.to_csv(output_file, index=False)

    print("Preprocessing selesai")
    print("Shape akhir:", df.shape)


if __name__ == "__main__":
    preprocessing_data(
        "../retail_sales_raw/retail_sales.csv",
        "dataset_preprocessing.csv"
    )